export const SEARCH_USERS = "SEARCH_USERS";
export const GET_USER = "GET_USER";
export const CLEAR_USERS = "CLEAR_USERS";
export const GET_REPOS = "GET_REPOS";
export const SET_LOADING = "SET_LOADING";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const INCREASE_PRODUCT_QUANTITY_IN_CART =
  "INCREASE_PRODUCT_QUANTITY_IN_CART";
export const DECREASE_PRODUCT_QUANTITY_IN_CART =
  "DECREASE_PRODUCT_QUANTITY_IN_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";
export const CLEAR_CART = "CLEAR_PRODUCTS_IN_CART";
export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
